### ISSUE TITLE
Is it possible to compare two chains?

### ISSUE THREAD

**Issue by Uendert** [fkoehlin/post_process_mcmcs#1]
Hi Fabian,

First of all, thanks for compiling such nice tools and make them available.

I did some plots using  [make_all.py](https://github.com/fkoehlin/post_process_mcmcs/blob/master/make_all.py), and now I wanted to compare two sets of chains. Similarly to what MontePython does like: `python /path/to/montepython_public/montepython/MontePython.py info /path/to/your/MontePython/chain_kids-1000-MH/ /path/to/your/MontePython/chain_kids-1000-NS/`

Is there a way to do that?

Thanks for your valuable time,
Uendert  

ps: I fixed some python3 related  bugs here: https://github.com/Uendert/post_process_mcmcs

**Comment by fkoehlin** [comment]
Hi Uendert,

please also have a look at the scripts individually. I don't recall if comparing two (or more) chains is possible for all scripts (or in 'make_all.py') but at least for the 2D contour plots it is possible (having had the usual comparison of Planck vs. my own measurements etc. in mind):

 make_2D_contour(path_out, paths_in=[path_in], ranges_2D_contour=ranges_2D_contour, labels_ctr=['test'], colors=['blue'], key_params=['Omega_m', 'sigma8'], fname_suffix=fname_suffix, levels=np.array([68.27, 95.45]) / 100., plot_filetypes=['.pdf'], smooth=1., nbins=50)

If you supply in 'paths_in' a list with paths to different chains, the script will plot the contours of all chains it can find in the same figure and you can customize 'labels', 'colors; etc. by supplying lists in the same ordering as your chains. Please check out the other plotting scripts, too, I might have included it in most but I agree that it's very poorly documented...

Feel free to improve the code, documentation and also please supply your Python3 related bugfixes via a 'pull request' (check out the Git documentation for how to proceed if it's your first time. :-) ).

Thanks,
Fabian

**Comment by Uendert** [comment]
Hi Fabian,

thanks for your reply and encouragement!

I'm wondering how I am supposed to supply 'paths_in' as a list of chains.  I tried something similar to:

`python make_all.py/plot_2D_contours.py path/to/chains_kids path/to/chains_planck  'model_name_1' 'model_name_2'  ' MH' ''`, but none of these works.

So for this works, should I use `sys.argv` to pass the chain's path to the scrip, so they know where to look for the chains?

Since you said you've done this to plot 2D contour plots for Planck's and your chains, I am assuming there is a better way than mine above idea: which involves a modification of the code.

Cheers,
Uendert

**Comment by fkoehlin** [comment]
Hi Uendert,

indeed you cannot supply a list of paths in at the moment from the command line. You'd need to implement your own command line parser for that (don't use sys.argv like I did...).
For the current implementation to work you really need to supply a list of paths manually by modifying the corresponding script itself. It's not very handy for many different plots etc. so if that's what you need, have a look at how to implement and user "argparse", that's much better than sys.argv!

Feel free to make a pull request once you've implemented argparse.

Cheers,
Fabian
